# Generated by Django 4.0 on 2021-12-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата подписания договора')),
                ('zakazchik', models.CharField(max_length=100, verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер отдела')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=250, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=50, verbose_name='Отчество')),
                ('zarplata', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Зарплата')),
                ('ruk', models.BooleanField(default=False, verbose_name='Руководитель в отделе')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория')),
                ('n_otdela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.otdel', verbose_name='Номер отдела')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('opis', models.CharField(max_length=255, verbose_name='Описание проекта')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость проекта')),
                ('dogovori', models.ManyToManyField(to='mainapp.Dogovor', verbose_name='Договоры по проекту')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('opis', models.CharField(max_length=100, verbose_name='Описание')),
                ('n_otdela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.otdel', verbose_name='Номер отдела')),
            ],
        ),
        migrations.AddField(
            model_name='dogovor',
            name='n_otdela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.otdel', verbose_name='Номер отдела'),
        ),
    ]
